title: "Charlie Talucci"
description: "A personal collection of images, writing, and things I find interesting."
url: ""
baseurl: "/Website-Build"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Collections
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
